# Generated by Django 5.1.4 on 2025-01-01 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rentals", "0003_booking_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
